- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - debug:
        msg: "{{ GITHUB_VARS }}"
    - debug:
        msg: "{{ GITHUB_VARS.VAR1 }}"
    - debug:
        msg: "{{ GITHUB_VARS.VAR2 }}"
