name: Branch Delete

on:
  delete:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: payload
      run: |
        echo "GITHUB_SHA is ${{ github.sha }}"
        echo "GITHUB_REF is ${{ github.ref }}"
        echo "${{ github.event.ref }} - ${{ github.event.ref_type }}"
    
    - name: print
      run: env
      
    - uses: actions/checkout@v3
    
    - run: git status
