name: Branch Delete

on:
  delete:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: payload
      run: |
        echo "${{ github.event.ref }}"
        echo "${{ github.event.ref_type }}"
    
    - name: print
      run: env
