name: C/C++ CI

on:
  push:
    paths-ignore: '.github/**'
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make & run
      run: |
        make
        ./exec > execout.txt
    - name: Save make output
      uses: actions/upload-artifact@v2
      with:
        name: exec-output
        path: execout.txt
