name: Test anything

on:
  - push
  - workflow_dispatch

jobs:
  print:

    runs-on: ubuntu-latest

    steps:
    - name: Get User
      run: whoami
    - name: print env
      run: env
    - name: AWS CLI
      run: aws --version
    - name: Ansible
      run: ansible --version
    - name: Docker
      run: docker -v
    - name: Pip3 version
      run: pip3 --version
    - name: Install boto
      run: sudo pip3 install boto3
    - name: Show boto
      run: pip3 show botocore
    - name: test boto
      run: echo import boto3 | python3
    - name: Run ansible inventory
      run: ansible -a ls -i aws_ec2.yml --graph
