name: Test anything

on:
  - push
  - workflow_dispatch

jobs:
  print:

    runs-on: ubuntu-latest

    steps:
    - name: Get User
      run: whoami
    - name: print env
      run: env
    - name: AWS CLI
      run: aws --version
    - name: Ansible
      run: ansible --version
    - name: Ansible modules
      run: ls -l /opt/pipx/venvs/ansible-core/lib/python3.8/site-packages
    - name: Docker
      run: docker -v
    - name: Pip3 version
      run: pip3 --version
    - name: Install boto
      run: sudo pip install boto3
    - name: Show boto
      run: pip show botocore
    - name: Show ansible
      run: pip show ansible
    - name: test boto
      run: echo import boto3 | python3 
