name: Test anything

on:
  workflow_dispatch:
  pull_request:
    branches: main
  push:

jobs:
  print:

    runs-on: ubuntu-latest

    steps:
    - name: print event
      run: echo ${{ github.event }}
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4
    - name: Set environment variables
      run: echo "TEST_VAR='test value'" >> $GITHUB_ENV
    - name: print env
      run: |
        env
        echo ${{ env.TEST_VAR }}
    - run: |
        echo ${{ github.ref }}
        echo ${{ github.head_ref }}
    - name: list cur dir
      run: ls -al
    - uses: actions/checkout@v2
    - name: list cur dir
      run: ls -al
    - name: print git config
      run: git config --list
    - name: print git branches
      run: git branch -a
    - name: list home dir
      run: ls -al ~/
    - name: Ansible
      run: >
        ansible-playbook --version &&
        cat /opt/pipx_bin/ansible &&
        which ansible-playbook &&
        which ansible-inventory &&
        which ansible
    - name: Show pipx packages
      run: pipx list
    - name: Check python
      run: ls -lr /usr/bin/python*
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Run ansible inventory
      run: ansible-inventory -i aws_ec2.yml --graph

