name: Test anything

on:
  - push
  - workflow_dispatch

jobs:
  print:

    runs-on: ubuntu-latest

    steps:
    - name: print env
      run: env
    - name: AWS CLI
      run: aws --version
    - name: Ansible
      run: ansible --version && cat /opt/pipx_bin/ansible
    - name: Install boto
      run: pip install boto3 && pip install botocore
    - name: Check python sites
      run: >
        /opt/pipx/venvs/ansible-core/bin/python -m site &&
        /opt/pipx/venvs/ansible-core/bin/python3 -m site &&
        /usr/bin/python3 -m site && 
        echo =============================== &&
        cat /opt/pipx/venvs/ansible-core/bin/activate* &&
        cat /opt/pipx/venvs/ansible-core/bin/Activate*
    - name: Check python
      run: ls -lrt /usr/bin/python* && ls -lrt /opt/pipx/venvs/ansible-core/bin/
    - name: check pipx modules
      run: ls -lrt /opt/pipx/venvs/ansible-core/lib/python3.8/site-packages/
    - name: Show boto
      run: pip show boto3
    - name: test boto
      run: echo import boto3 | /usr/bin/python3
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run ansible inventory
      run: ansible-inventory -i aws_ec2.yml --graph
