name: Test anything

on:
  - push
  - workflow_dispatch

jobs:
  print:

    runs-on: ubuntu-latest

    steps:
    - name: Get User
      run: whoami
    - name: print env
      run: env
    - name: AWS CLI
      run: aws --version
    - name: Ansible
      run: ansible --version
    - name: Docker
      run: docker -v
    - name: Check python
      run: which python
    - name: Check python
      run: ls -lrt /usr/bin/python*
    - name: Install boto
      run: sudo pip install boto3 && sudo pip install botocore
    - name: Show boto
      run: pip show boto3
    - name: Checkout
      uses: actions/checkout@v2
    - name: test boto
      run: echo import boto3 | python3
    - name: Run ansible inventory
      run: ansible-inventory -i aws_ec2.yml --graph
