name: Test anything

on:
  - push
  - workflow_dispatch

jobs:
  print:

    runs-on: ubuntu-latest

    steps:
    - name: print env
      run: env
    - name: list home dir
      run: ls -al ~/
    - name: AWS CLI
      run: aws --version
    - name: Ansible
      run: ansible-playbook --version && cat /opt/pipx_bin/ansible
    - name: Show pipx packages
      run: pipx list
    - name: Install boto
      run: pipx inject ansible-core boto3 --include-deps --include-apps && pipx inject ansible-core botocore --include-deps --include-apps
    - name: Check python sites
      run: >
        /opt/pipx/venvs/ansible-core/bin/python -m site &&
        /opt/pipx/venvs/ansible-core/bin/python3 -m site &&
        /usr/bin/python3 -m site && 
        echo =============================== &&
        cat /opt/pipx/venvs/ansible-core/bin/activate* &&
        cat /opt/pipx/venvs/ansible-core/bin/Activate*
    - name: test boto
      run: echo import boto3 | /opt/pipx/venvs/ansible-core/bin/python
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run ansible inventory
      run: ansible-inventory -i aws_ec2.yml --graph
