name: Test anything

on:
  - push
  - workflow_dispatch

jobs:
  print:

    runs-on: ubuntu-latest

    steps:
    - name: Get User
      run: whoami
    - name: print env
      run: env
    - name: AWS CLI
      run: aws --version
    - name: Ansible
      run: ansible --version
    - name: Docker
      run: docker -v
    - name: Pip version
      run: pip --version
    - name: Install boto
      run: pip install boto3
    - name: Show boto
      run: pip show botocore
