name: Test anything

on:
  - push
  - workflow_dispatch
  - pull_request

jobs:
  print:

    runs-on: ubuntu-latest

    steps:
    - name: Set environment variables
      run: echo "TEST_VAR='test value'" >> $GITHUB_ENV
    - name: print env
      run: env
    - name: list home dir
      run: ls -al ~/
    - name: Install certbot
      run: sudo apt-get install certbot python3-certbot-dns-route53
    - name: Install boto
      run: pip install boto3 && pip install botocore
    - name: Install boto
      run: pipx inject ansible-core boto3 --include-deps --include-apps && pipx inject ansible-core botocore --include-deps --include-apps
    - name: Ansible
      run: >
        ansible-playbook --version &&
        cat /opt/pipx_bin/ansible &&
        which ansible-playbook &&
        which ansible-inventory &&
        which ansible
    - name: Show pipx packages
      run: pipx list
    - name: Check python
      run: ls -lr /usr/bin/python*
    - name: test boto
      run: echo import boto3 | /opt/pipx/venvs/ansible-core/bin/python
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run ansible inventory
      run: ansible-inventory -i aws_ec2.yml --graph

