name: Test anything

on:
  - push
  - workflow_dispatch

jobs:
  print:

    runs-on: ubuntu-latest

    steps:
    - name: print env
      run: env
    - name: list home dir
      run: ls -al ~/
    - name: Install boto
      run: pip install boto3 && pip install botocore
    - name: Install boto
      run: pipx inject ansible-core boto3 --include-deps --include-apps && pipx inject ansible-core botocore --include-deps --include-apps
    - name: Ansible
      run: >
        ansible-playbook --version &&
        cat /opt/pipx_bin/ansible &&
        which ansible-playbook &&
        which ansible-inventory &&
        which ansible
    - name: Ansible collection
      run: ls -lr /opt/pipx/venvs/ansible-core/lib/python3.8/site-packages/ansible
    - name: find amazon aws_ec2.py
      run: sudo find / -iname aws_ec2.py 
    - name: find amazon cloudformation
      run: sudo find / -iname cloudformation.py
    - name: find boto3
      run: sudo find / -iname boto3 
    - name: find botocore
      run: sudo find / -iname botocore
    - name: Show pipx packages
      run: pipx list
    - name: Check python
      run: ls -lr /usr/bin/python*
    - name: test boto
      run: echo import boto3 | /opt/pipx/venvs/ansible-core/bin/python
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run ansible inventory
      run: ansible-inventory -i aws_ec2.yml --graph

